name: PM-PluginTemplate
main: space\yurisi\RegisterSystem
author: yurisi
# depend:
#   - EconomyAPI
version: 1.0.0
api: 4.0.0
# permissions:
#   space.yurisi.RegisterSystem.example:
#     default: op
#     description: 詳細